### ISSUE TITLE
Shop refresh

### ISSUE THREAD

**Issue by att3** [Znote/ZnoteAAC#151]
If you purchase an item from the shop and refresh the page it will buy the item again.

**Comment by peonso** [comment]
$pageWasRefreshed = isset($_SERVER['HTTP_CACHE_CONTROL']) && $_SERVER['HTTP_CACHE_CONTROL'] === 'max-age=0';
	if($pageWasRefreshed ) {
	   $_POST = array();
	}

**Comment by peonso** [comment]
After line https://github.com/Znote/ZnoteAAC/blob/a23b38090da6559c8259008b296e67b120d3a253/shop.php#L9
    if ($_SESSION['session'] == $_POST['session']){
After line https://github.com/Znote/ZnoteAAC/blob/a23b38090da6559c8259008b296e67b120d3a253/shop.php#L64
    }
After line https://github.com/Znote/ZnoteAAC/blob/a23b38090da6559c8259008b296e67b120d3a253/shop.php#L107
    <input type="hidden" name="session" value="<?php echo time(); ?>">
After line https://github.com/Znote/ZnoteAAC/blob/a23b38090da6559c8259008b296e67b120d3a253/shop.php#L134
    $_SESSION['session'] = time();
