### ISSUE TITLE
question, why is the server information not showing the info?

### ISSUE THREAD

**Issue by mimusassasin** [Znote/ZnoteAAC#177]
the page seems to be well charged, but in the server rates says X and in the server info show an - , what could it be?
##

**Comment by Znote** [comment]
My plan was to create a server config parser of sorts, as config.lua and stages is not files that are frequently being updated, there is:
1: no need to reload the file every time a visitor enters the page
2: no need to give www-data access to ot directory

But it will require mediocre php knowledge, a newline parser for config.lua and an xml parser for the stages.

/special/otparser.php
-> convert relevant public-friendly variables from config.lua to a json cache format
-> convert stages.xml, spells and monsters to json cache format.
