### ISSUE TITLE
problems with paypal

### ISSUE THREAD

**Issue by mimusassasin** [Znote/ZnoteAAC#184]
hello! im having a little problem with paypal, paypal is sendingme some emails like this

Please check your server that handles PayPal Instant Payment Notification (IPN) messages. Messages sent to the following URL(s) are not being received:

you know if the payments are getting back? or incompleted? or theres no try to pay?

tank u so much!

**Comment by slayingworld** [comment]
Same problem here, :[

**Comment by Raggaer** [comment]
Znote AAC should start using (https://github.com/paypal/PayPal-PHP-SDK) (if not already) for paypal.
Also check your IPN something may be wrong with that...

**Comment by Znote** [comment]
Related to #222
