### ISSUE TITLE
Creating Account, email verification..

### ISSUE THREAD

**Issue by slayingworld** [Znote/ZnoteAAC#188]
Whenever you create a new account  using znote, it gives the page that an email has been sent to the email address you registered under the account. Doesn't matter if on config.php you set the settings to not do that.

**Comment by forgee** [comment]
I have encountered the same thing. You don't actually have to activate the account, it just says that you do.
[register.php Line 85](https://github.com/Znote/ZnoteAAC/blob/master/register.php#L85) should be `if ($config['mailserver']['register']) {`
I don't have git setup on this computer. Perhaps someone else could fix it, else I'll try to submit a PR some other time.
