### ISSUE TITLE
Default layout

### ISSUE THREAD

**Issue by att3** [Znote/ZnoteAAC#191]
The current layout seems a bit outdated / unprofessional. Not sure if it's just me.

Sure, there are plenty of layouts at otland for ZnoteACC, but I've noticed that majority of the ACC users start using some layout based on bootstrap.
Therefore I am going to suggest: Change the current layout to some simple layout based on bootstraps framework.

Pros: More responsive, more "modern" looking, easy to customize, there are plenty of snippets and tutorials for bootstrap.
Cons: ?
##

**Comment by Znote** [comment]
I kinda want to make a RESTful template for Znote AAC to challenge the API system. I think it has potential but haven't been used before, and it may help if I make a base template so other people can see how it works. 

I am not sure what I should use on the frontend though, I want to give Angular.js a shot, or make my own frontend controller. Do you know any free bootstrap template that could be good to use as default template that I can use as a base?

**Comment by TwistedScorpio** [comment]
Znote, can you reupload the dark tibia template ? I can't find it anywhere!

**Comment by gpedro** [comment]
wow! RESTful API + Angular.js LGTM! I can help it. I already have some experience in nodejs (workflow optimization) and angular as frontend framework.

**Comment by Znote** [comment]
Yeah, I created the AngularJS frontend on DevelopersPL DevAAC repository. I have started looking into AngularJS 2 recently, but I want it to get out of beta before I start playing with it here. 

It may be best if I start on the base REST template, as I need to optimize the RESTful API. 

In case you are curious, I already have the API base system roughly set up:
http://demo.znote.eu/api/?debug

Sample module (topExperience.php)

http://demo.znote.eu/api/modules/highscores/topExperience.php?rows=5&debug

If you enter links without debug as an url parameter, it will return normal json which can be read by something like ajax in Angular or jquery etc.

**Comment by att3** [comment]
^ Seems great.

I've been playing quite a lot with DevAAC lately, and IMHO it's awesome.. once you learn the frameworks.

It's backend is something that you can actually pick up very fast, and it feels very user friendly.

But with AngularJS, the learning curve has been quite wide for me and taken plenty of time. It is not as simple as it first might seem, often you can't really "conclude" that much, you need to read the docs a lot.. But! Once you learn it enough, it's actually very nice.

I believe this(the learning curve of angularJS) is one major reason why people aren't using DevAAC, although the AAC itself i's very good and user friendly. 

I have also looked into Angular 2, and tried to understand it.
In my experience, it's **much** easier to understand and more importantly, once you learn the very basics of it, you can do A lot with it, _the pieces just fit together_, unlike with AngularJS (too often)

So lastly, how about combining DevAACs backend with Angular2?

So far I've found that backend very nice, easy to learn and easily expandable.
IMO AngularJS 2 has very simple way of doing things, making it easy to understand / pick up, unlike angularJS (don't get me wrong, Angular1 is great, too).

**Comment by Znote** [comment]
@att3 

Yeah, but that would be a natural upgrade to DevAAC, not Znote AAC. :p 
And as explained on your issue over there, I am not quite set on Angular 2 yet either, there are a few issues pointed out by me and Daniel Speichert. And Znote AAC is suppose to be as dependency free as possible.

**Comment by Raggaer** [comment]
Using Angular2 just puts a more complex entry barrier for newcomers. I think the layout is something the server owner sohuld take care of

**Comment by gpedro** [comment]
we can solve this issue just by adding a template engine

**Comment by Znote** [comment]
May want to look into Twig, though alot of rework would be needed to make it work, and there will definitely be a performance cost for using a template engine, and if done wrong, can be a barrier to entry, especially if you are into researching and hacking new things into the core. 

You can override default pages in the layout folder, so you could create a layout isolated environment using a template engine to try it out without modifying any default Znote AAC files (beside the layout folder). It would be a nice experiment.

**Comment by gpedro** [comment]
ModernAAC uses [Smarty](http://www.smarty.net) as template engine and they did a simple logic to override a main layout separating by controller or controller and method .
https://github.com/celopeccin/modernaac/blob/master/index.php#L187-L193

**Comment by Raggaer** [comment]
Blade is also a good option. So we can get rid of the mix of PHP + HTML

**Comment by Znote** [comment]
I have gotten permission from Mark to use the shadowcores layout as the new default template for Znote AAC. Which looks very similar to this: http://www.tibijka.net/

However many changes will need to occur to the core files to support it, so I think I will make a compatibility branch for older released layouts. Not entirely set if I shall change the default layout before the official 1.5 release, or have it as one of the first thing i do in 1.6. I think the change is significant enough to change the version number.

**Comment by glombers** [comment]
enough for me this layout which is not know how to you. just think and use the
`<html>'
'<head>`
'<body>'
'</body>'
'</head>'
`</html>'
It has nothing to do with angularjs because you can use it even in version 1.4
![enter image description here](http://i.imgur.com/EE6m3Qf.gif)

**Comment by MatheusGrilo** [comment]
Someone is working on it? Need help?

**Comment by Znote** [comment]
I will begin to work on this after the official release of 1.5, which I hope is within 2-3 weeks.

**Comment by Znote** [comment]
Because of obsolete dependencies in the old layout, I switched it out with AtomIO dark layout. Its not optimal but will have to do for now, a new default layout will be evaluated after the launch of 1.6. (1.5 never came to fruition/ended up being a dev version).
