### ISSUE TITLE
Debug with the war system

### ISSUE THREAD

**Issue by rikitrini** [Znote/ZnoteAAC#193]
Hello znote, example of the debug: if i make a war with 10 frag, when i killed the 10 frags the war not finish never and if i try to disable the guild for me its ok but the another guy still on war and never finish so if u can fix it or something thanks!^^

**Comment by rikitrini** [comment]
Im going to detail more the debug exactly so  i make new war TEST VS TEST1   10 frag limit    when TEST guild make 10 frags, the war not end, still on war and counting frags if i disable the guild, on TEST guild  and logout im not on war but TEST1 still on war and never finishes  that was the problem exactly >.<

**Comment by rikitrini** [comment]
some one can help? still , tryng fix it for 3 days and no answer on any forum :/

**Comment by Znote** [comment]
I am to busy to create a local development environment and try to reproduce and fix this bug. But I will happily accept a pull request if anyone has the time to confirm and fix it.
