### ISSUE TITLE
´BUGED Shop system

### ISSUE THREAD

**Issue by rikitrini** [Znote/ZnoteAAC#196]
Hello bro if u can help but i got a problem cant buy any item it says
You have points. But not say the ammount of points so if i try to purchase anything it says i need to add more points that's my shop.php script http://pastebin.com/k1s8HN4Q
i tried to put too the item for 0 points, and it says 0: Account is not converted to work with Znote AAC
so without or with points can't do anything  i tried too put a item for 0 points and it says  0: Account is not converted to work with Znote AAC  if can u help me please, thanks for all mate.
and say on all accounts You have points-.-

**Comment by Znote** [comment]
Make sure you have created an account with Znote AAC, (not old acc from in-game acc manager or gesior etc) and try to give a player on that account some points. That should work assuming you have znote_accounts table installed?

**Comment by rikitrini** [comment]
yea thanks my friend that was the problem^^
