### ISSUE TITLE
bug on engine 1.1 in shop and playerdeath

### ISSUE THREAD

**Issue by mimusassasin** [Znote/ZnoteAAC#197]
player death 

Lua Script Error: [CreatureScript Interface] 
data/creaturescripts/scripts/others/playerdeath.lua:onDeath
data/creaturescripts/scripts/others/playerdeath.lua:78: attempt to concatenate local 'mostDamage_unjustified' (a boolean value)
stack traceback:
	[C]: in function '__concat'
	data/creaturescripts/scripts/others/playerdeath.lua:78: in function <data/creaturescripts/scripts/others/playerdeath.lua:35>

shop
Lua Script Error: [TalkAction Interface] 
data/talkactions/scripts/znoteshop.lua:onSay
data/talkactions/scripts/znoteshop.lua:16: attempt to call field 'getDataInt' (a nil value)
stack traceback:
	[C]: in function 'getDataInt'
	data/talkactions/scripts/znoteshop.lua:16: in function <data/talkactions/scripts/znoteshop.lua:2>
 

hello! tnk u for reeding, what would be this bugs?

**Comment by Znote** [comment]
@ninjalulz : Perhaps you got an idea what may be the problem?
db.storeQuery is saved into resultid and that statement checks through, but apparently there is no valid data that is returned?
Does TFS 1.1 handle db queries differently, or is there another problem here?

**Comment by ninjalulz** [comment]
Regarding playerdeath.lua, the fifth and sixth parameter returns a boolean value instead of numeric in TFS 1.1.

Replace L78 with this:
```Lua
db.query("INSERT INTO `player_deaths` (`player_id`, `time`, `level`, `killed_by`, `is_player`, `mostdamage_by`, `mostdamage_is_player`, `unjustified`, `mostdamage_unjustified`) VALUES (" .. playerGuid .. ", " .. os.time() .. ", " .. player:getLevel() .. ", " .. db.escapeString(killerName) .. ", " .. byPlayer .. ", " .. db.escapeString(mostDamageName) .. ", " .. byPlayerMostDamage .. ", " .. (unjustified and 1 or 0) .. ", " .. (mostDamage_unjustified and 1 or 0) .. ")")
```
Database result functions was recently updated, and getDataInt/getDataLong were renamed to getNumber.

**Comment by mimusassasin** [comment]
hello! i just try it and now the two scripts are working well, as i can tell, but now the guidwar page is bugged, when the limit of kills on the war is reached, the warstatus says ??? 


tnk for reeding i hope this could help ^^

**Comment by rikitrini** [comment]
@mimusassasin  just change on config.lua ??? for ended or what u want xd and solved
