### ISSUE TITLE
Guild creation error

### ISSUE THREAD

**Issue by woeterman94** [Znote/ZnoteAAC#198]
string(102) "INSERT INTO `guild_membership` (`player_id`, `guild_id`, `rank_id`, `nick`) VALUES ('3', '2', '', '');" 
(query - SQL error) 
Type: voidQuery (voidQuery is used for update, insert or delete from database)

Cannot add or update a child row: a foreign key constraint fails (`forgotten`.`guild_membership`, CONSTRAINT `guild_membership_ibfk_3` FOREIGN KEY (`rank_id`) REFERENCES `guild_ranks` (`id`) ON DELETE CASCADE ON UPDATE CASCADE)
##

**Comment by Znote** [comment]
Which TFS version are you using?
Have you configured config.php with correct TFS version?

**Comment by woeterman94** [comment]
TFS 1.0 and yes I changed it.

**Comment by woeterman94** [comment]
How do I solve this? Does it have something to do with the quotes?

**Comment by woeterman94** [comment]
Thanks for closing this..lmao

**Comment by Znote** [comment]
I assume its not a problem any longer? Its an old issue, and related to this:
#260 

Which was solved by adding the triggers.
