### ISSUE TITLE
Gesior -> Znote [$10]

### ISSUE THREAD

**Issue by olszak94** [Znote/ZnoteAAC#205]
Is there any conversion needed if i want to move from gesior acc to znote acc? (i've got already existing database with gesior). If it's required, is there any tool to do that ? Or tutorial?

edit
Please make it work again, since i would like to use ZnoteAAC.

**Comment by Znote** [comment]
We had this: https://github.com/Znote/ZnoteAAC/blob/master/special/database2znoteaac.php
But unfortunately I think its out-dated now.

**Comment by olszak94** [comment]
Soo, there's no way atm to go from gesior to znote ? :s
