### ISSUE TITLE
Paypal issue

### ISSUE THREAD

**Issue by Rivve** [Znote/ZnoteAAC#213]
Hey,

So tried getting Paypal to work without much success,
Downloaded the debug ini and ran it, and it gave me the following

Notice: Undefined index: item_name in C:\xampp\htdocs\ipn.php on line 77

Notice: Undefined index: item_number in C:\xampp\htdocs\ipn.php on line 78

Notice: Undefined index: payment_status in C:\xampp\htdocs\ipn.php on line 79

Notice: Undefined index: mc_gross in C:\xampp\htdocs\ipn.php on line 80

Notice: Undefined index: mc_currency in C:\xampp\htdocs\ipn.php on line 81

Notice: Undefined index: txn_id in C:\xampp\htdocs\ipn.php on line 82

Notice: Undefined index: receiver_email in C:\xampp\htdocs\ipn.php on line 83

Notice: Undefined index: payer_email in C:\xampp\htdocs\ipn.php on line 84

Notice: Undefined index: custom in C:\xampp\htdocs\ipn.php on line 85

So I found a "fix" on the otland forums which also didn't solve it
https://otland.net/threads/znoteaac-paypal-ipn-fix-not-100-tested.235573/

However it does handle the purchase but does not insert anything into the database.

Is there any fix out there?

Edit:
Got an updated cacert.pem file also running cURL

**Comment by Znote** [comment]
Related to: #222
