### ISSUE TITLE
problem with old DB and flags

### ISSUE THREAD

**Issue by mimusassasin** [Znote/ZnoteAAC#216]
hello! well i install the last updates and guess what? all the chars in the server does not have a flag, well they have a broken img, i add a row in znote_accouts named flag, but idk what else to add, can you helpme?

**Comment by Znote** [comment]
A link to your site would be helpful :)

**Comment by Znote** [comment]
For now just disable flags in config.php, it should hide the flags from characterprofile and highscores.
