### ISSUE TITLE
Changelog.php doesn't show logs

### ISSUE THREAD

**Issue by olszak94** [Znote/ZnoteAAC#218]
Changelog.php file is not showing logs until i add new one, but it's only showing when i add new one. If i go to main page or to `changelog.php` again it's temporarily gone

**Comment by HalfAway** [comment]
Sounds like a cache problem.
Is The folder cache writeable?

**Comment by olszak94** [comment]
Yea, I think so, didn't check but news are working and high scores too
W dniu śr., 21 paź 2015 o 06:36 Emil <notifications@github.com> napisał(a):

**Comment by olszak94** [comment]
I've checked, there's no file in `engine/cache` folder called `changelog.cache.php`

**Comment by Znote** [comment]
create an empty file called changelog.cache.php and make sure znote aac (www-data) have write access to it.

**Comment by olszak94** [comment]
I did everything as you said, still - no results.
