### ISSUE TITLE
Using ZnoteAAC API

### ISSUE THREAD

**Issue by olszak94** [Znote/ZnoteAAC#219]
How can i call ZnoteAAC API ? for example, to pull data of a player?
##

**Comment by Znote** [comment]
https://github.com/Znote/ZnoteAAC/blob/master/engine/function/users.php#L1246-L1279

```php
$player = user_data(player_ID, 'name', 'level');
echo "Character name: ". $player['name'] .". is level: ". $player['level'];
```

To find character id, you can use function user_character_id if you got the name. 
```php
$cid = user_character_id("Chaosruler");
$player = user_data($cid, 'name', 'level');
echo "Character name: ". $player['name'] .". is level: ". $player['level'];
```

**Comment by olszak94** [comment]
For me the `topExperience.php` doesn't work. And yes, i ment using api & api modules.

**Comment by Znote** [comment]
Dosn't work? Thats odd, it works for me on my local site and the demo site.

**Comment by olszak94** [comment]
Maybe i have to set chmod/chown on some files ? Like with cache?

- -
Rafał Olszewski

Dnia 26 paź 2015 o godz. 13:47 Stefan A. Brannfjell <notifications@github.com> napisał(a):

**Comment by Znote** [comment]
No. Do you get any error messages? What system do you use?

**Comment by olszak94** [comment]
No errors, just blank page. I'm using Ubuntu 14.04 x64

W dniu wt., 27 paź 2015 o 19:26 Stefan A. Brannfjell <
notifications@github.com> napisał(a):
