### ISSUE TITLE
javascript:window.location.href

### ISSUE THREAD

**Issue by thatmichaelguy** [Znote/ZnoteAAC#225]
The issue:
Links such as the following do not work as intended, and instead navigate your browser to http://_/webpage.php?foo=bar
```
$url = url("guildwar.php?warid=". $wars['id']);
echo '<tr class="special" onclick="javascript:window.location.href=\'' . $url . '\'">';
```

The solution as suggested by Codex NG [here](https://otland.net/threads/php-js-znote-aac-href-issue.239980/):
```
$url = "guildwar.php?warid=". $wars['id'];
echo '<tr class="special" onclick="javascript:window.location.href=\'' . $url . '\'">';
```

**Comment by gpedro** [comment]
what environment are you using? php, apache version, operational system ?

**Comment by thatmichaelguy** [comment]
I believe issue #182 is the same as this issue.
To answer your question though, I replicated this on Windows 10 running Apache 2.4.17 PHP 5.6.15 and Ubuntu 15.04 running NGINX with PHP5-FPM.
