### ISSUE TITLE
Recovery Account

### ISSUE THREAD

**Issue by caiografit** [Znote/ZnoteAAC#226]
Hi guys

How can i configure PHPMailer to send e-mails from recovery.php?

I tried to configure without success.

Thanks

**Comment by Weeboo** [comment]
https://github.com/Znote/ZnoteAAC/blob/master/config.php#L520

**Comment by Znote** [comment]
This may be related to #245, which should be fixed now. 
Now you can configure username for the smtp service, and email to send from. Before those were configured to be the same, which is not always the case.
