### ISSUE TITLE
how add new character to the aution ?

### ISSUE THREAD

**Issue by Crixpx** [Znote/ZnoteAAC#230]
how add new character to the aution ?

**Comment by Znote** [comment]
Functionality never completed, so now you can't. 
I was considering removing it from the repo since its incomplete, but decided to keep it just to remind myself to complete it someday.

**Comment by Crixpx** [comment]
thanks :) :+1:

**Comment by gpedro** [comment]
@Znote it's unnecessary auction system for "default" znote-acc, maybe we can distribute with a complement.
