### ISSUE TITLE
PHPMailer, ZnoteAAC, SMTP accounts.. not compatible, easy to fix :)

### ISSUE THREAD

**Issue by gesior** [Znote/ZnoteAAC#245]
In this line, AAC sets 'from mail' to SMTP server account 'username':
    
    $mail->setFrom($this->_config['username'], $this->_config['fromName']);
    
https://github.com/Znote/ZnoteAAC/blob/master/engine/function/mail.php#L60

Arguments for 'setFrom' of PHPMailer are:

-string, e-mail address [or person that send e-mail]
-string, name [of person that send e-mail]

    
    if (($pos = strrpos($address, '@')) === false or
    
https://github.com/PHPMailer/PHPMailer/blob/master/class.phpmailer.php#L1006

In most cases SMTP account usernames are like 'gesior@is.noob' 'znote@znote.com', so it works fine, but there are also mass mail services with usernames like '1.gillwings.smtp' and then AAC shows error:
_Invalid address: (setFrom) 1.gillwings.smtp_
(debug mode)

**Comment by Znote** [comment]
Aha, yes! Thanks for your help. :+1:
