### ISSUE TITLE
Correct vocation name in "Highscore" & "Online List"

### ISSUE THREAD

**Issue by brewsterl** [Znote/ZnoteAAC#246]
My promotion NPCs promote the player using:

> node1:addChildKeyword({'yes'}, StdModule.promotePlayer, {npcHandler = npcHandler, cost = 200000, level = 20, **_promotion = 1_**, text = '...'})

With this alone I fix on CharacterProfile.php:
https://otland.net/threads/znote-acc-correct-vocation-name-in-character-profile.202676/

But how i can fix in **Highscore.php** & **OnlineList.php**, only shows the vocation without promotion
##

**Comment by Znote** [comment]
onlinelist.php uses this data source: 
https://github.com/Znote/ZnoteAAC/blob/master/engine/function/general.php#L285-L286

highscore.php uses this data source, but then proceeds to cache it for up to an hour:
https://github.com/Znote/ZnoteAAC/blob/master/engine/function/users.php#L891,L919

$data[7] represents the data source for etc experience.
