### ISSUE TITLE
Pagseguro Automatico Error!

### ISSUE THREAD

**Issue by EmersonHenriique** [Znote/ZnoteAAC#247]
notificationCode or notificationType is empty. Type: , Code: 
Connection from IP: 186.234.16.9
##

**Comment by K3V1N-BR** [comment]
I followed the instructions from (gpedro) at the (pagseguro_retorno.php), but when I completed the payment the points doesn't come. Someone had this problem ?

**Comment by Znote** [comment]
Fixed in pull request #253
