### ISSUE TITLE
Allow users to disable 2FA

### ISSUE THREAD

**Issue by ninjalulz** [Znote/ZnoteAAC#249]
I think it would be nice if users had the possibility to disable 2FA. Some users might be clumsy, so it's essential to provide them with a way to login with an one-time token (in case they lose their token generator) which disables their secret key.

**Comment by Znote** [comment]
My current plan is to integrate it to the email recovery system, not sure if there is any other good way of doing this that dosn't compromise security?

**Comment by ninjalulz** [comment]
I can't think of any viable solution atm, but integrating it to the email recovery system might suffice. :p
