### ISSUE TITLE
Showing outfits and mounts

### ISSUE THREAD

**Issue by glombers** [Znote/ZnoteAAC#252]
Let's build script showing outfits and mounts on:
- online list
- character profile

**Comment by joseluis2g** [comment]
easy to add

**Comment by Raggaer** [comment]
I dont know if Znote ships with an outfit generator.

I guess this wont do it to the main repository (for obvious reasons) so your best bet is to take an outfit generator from otland and add the image by yourself. If you need help message me at Otland

**Comment by Znote** [comment]
Baram:
[outfit.znote.eu](http://outfit.znote.eu/)
![Image server](http://outfit.znote.eu/?a=514&b=2&c=45&d=13&e=65&f=1&g=66083&&h=2&i=3)

Official outfit server. Code is a clone of https://github.com/renatorib/tibia-outfitter, which again is based on Gesior. 
Now we just got to load from that URL. Still need to look into retrieving outfits everywhere. This will make pretty big cache files if enabled.
