### ISSUE TITLE
Nginx error.log

### ISSUE THREAD

**Issue by glombers** [Znote/ZnoteAAC#255]
[error] 325#0: *1160 FastCGI sent in stderr: "PHP message: PHP Warning:  fopen(engine/cache/topPlayer.cache.php): failed to open stream: Permission denied in /var/www/html/engine/function/cache.php on line 91

I use this setting
`chown www-data:www-data -R /var/www/html`

**Comment by tedbro** [comment]
Off the read me file, number 8 stated to change the rights of the  /engine/cache. It looks like line 91 saves data to the appropriate cache folder and its not getting the appropriate rights to write to the folder.

8: You may need to change directory access rights of /engine/cache to allow writing.

**Comment by Znote** [comment]
Try to give the file engine/function/cache.php write access.
'chmod 644 /var/www/html/engine/function/cache.php'

**Comment by glombers** [comment]
@Znote I now have such problems
http://pastebin.com/7D91L7KY

**Comment by Raggaer** [comment]
I dont really see anything other than some GET requests. care to elaborate please

**Comment by Znote** [comment]
That looks like an access log, serving a cached image file, a redirect to frontpage, a visit to characterprofile. No errors.
