### ISSUE TITLE
SQL void Query when creating guild

### ISSUE THREAD

**Issue by kito2** [Znote/ZnoteAAC#260]
I am having this problem:

![image](https://cloud.githubusercontent.com/assets/21250744/21468818/ac83c050-ca07-11e6-9680-c3ec7de7caf9.png)

![image](https://cloud.githubusercontent.com/assets/21250744/21468854/fe195a68-ca09-11e6-947d-61c2b2389972.png)

How to fix this?

**Comment by Raggaer** [comment]
Your query might be wrong. The second picture says there is a duplicate entry. 

The problem might be (as seen on the pictures) that you are leaving rank_id empty?

**Comment by kito2** [comment]
The code is exactly as it is here.

What happened, made a reset of all players (downgraded to level 8), truncated table guilds, guild_member, guild_kill, guild_rank, etc... And now having this problem.

**Comment by Raggaer** [comment]
On the first picture rank_id is empty. So I guess its not a valid foreign key value.

Also you cant truncate a table that contains a foreign key constraint without dropping the fkeys

**Comment by kito2** [comment]
@Raggaer how you do that?

**Comment by kito2** [comment]
It seems that the guild is created, but the rank are not inserted on the table.

**Comment by kito2** [comment]
Somehow the triggers got deleted, the solution: add them again.
