### ISSUE TITLE
Character Comment BUG

### ISSUE THREAD

**Issue by glombers** [Znote/ZnoteAAC#261]
When a player bets enter the changed comment. Displaying page shows like this:

Hi\r\nHI

and should be so:
Hi
r
nHI

**Comment by Raggaer** [comment]
Well that message should look like

Hi
HI

No idea where you are getting those r and n letters. `\` doesnt mean newline. `\n` does
On Windows you can use `\r\n` but `\n` is usually enough.

There is `nl2br` to convert new lines to HTML `<br>` tags

**Comment by glombers** [comment]
https://github.com/Znote/ZnoteAAC/blob/master/characterprofile.php#L205
http://php.net/manual/en/function.nl2br.php
