### ISSUE TITLE
Gallery isn't retrieving the correct LINK

### ISSUE THREAD

**Issue by kito2** [Znote/ZnoteAAC#263]
Gallery is not working when trying to show an uploaded image:

![image](https://cloud.githubusercontent.com/assets/21250744/21522872/124b83ae-cce8-11e6-9348-c772f909337b.png)

![image](https://cloud.githubusercontent.com/assets/21250744/21522877/18747e2a-cce8-11e6-8558-ce66e19295a8.png)

**Comment by kito2** [comment]
I have been using LightShot for over 2 years to upload images and never got deleted one.

They upload their images to: http://prntscr.com/dp0qsh - So it may be a good suggestion.

**Comment by Znote** [comment]
Looks good, I will convert the gallery to support http://prnt.sc/ as the image host.

**Comment by Znote** [comment]
Hmm, problem with prnt.sc/lighshot is that you don't get access to the direct URL.

**Comment by kito2** [comment]
Znote, 

It works but they are a few issues:

![image](https://cloud.githubusercontent.com/assets/21250744/21580762/fa4239ca-cfed-11e6-9764-780ec5bbcc5e.png)

As you can see the Tittle was truncated and also the "/" was added.

**Comment by kito2** [comment]
Also there is a bug when the image is not a square: 
![image](https://cloud.githubusercontent.com/assets/21250744/21580776/51d8e46c-cfef-11e6-8cd0-984376e0262b.png)

**Comment by Znote** [comment]
@kito That is only related to your private repo, created by [joseluis2g](https://github.com/kito2/znote/blob/f8e0475c84ac4d26e3683e578f375f161ca5e216/gallery.php#L90)

**Comment by kito2** [comment]
Oh sry thought it was problem from here... thanks.

**Comment by Fiimpz** [comment]
Anyone solved this? imgur or smth is good otherwise?

**Comment by Znote** [comment]
I see, the bi-yearly image host is down, time to implement a new one. x) 
I'll look into the imgur API, they seem to support uploading and retrieving direct links. But requires site owner to have an imgur account and register an app (to get token and secret keypairs for the API). 
But it seems more stable than the other alternatives out there.

**Comment by Fiimpz** [comment]
Is this fixed with another url? Maybe imgur? or smth

**Comment by Znote** [comment]
Gallery should now be fixed with imgur, see wiki for installation instructions:
https://github.com/Znote/ZnoteAAC/wiki/IMGUR-powered-Gallery-page
