### ISSUE TITLE
market.php is ussing to much resources.

### ISSUE THREAD

**Issue by kito2** [Znote/ZnoteAAC#264]
Znote,

The market.php is a great idea and I loved it, but it is using a lot of resources, you can check on live @.

It would be good to optimize this script by sorting max 10-15 items per page.

**Comment by Raggaer** [comment]
How is it using more resources than any other page? We need logs or something from your http server

Also resources are there to be used

**Comment by kito2** [comment]
Ok, give a try at this www.mtibia-global.com/market.php
