### ISSUE TITLE
BUG! 

### ISSUE THREAD

**Issue by glombers** [Znote/ZnoteAAC#272]
It does not work text wrapping on the forum about the length of one word fI suspect that we need to add features [wordwrap](http://php.net/manual/en/function.wordwrap.php)

**Comment by Znote** [comment]
Could you reproduce the bug for me on http://ortz.znote.eu/
?

**Comment by glombers** [comment]
http://ortz.znote.eu/forum.php?forum=Discussion&cat=3&thread=1
http://ortz.znote.eu/forum.php?forum=Discussion&cat=3&thread=2
