### ISSUE TITLE
change title of the page AFTER including header.php?

### ISSUE THREAD

**Issue by glombers** [Znote/ZnoteAAC#274]
This could be added to any page then it looks better

example:

`<?php require_once 'engine/init.php'; include 'layout/overall/header.php'; `

```
$buffer=ob_get_contents();
ob_end_clean();
$title = "page title";
$buffer = preg_replace('/(<title>)(.*?)(<\/title>)/i', '$1' . $title . '$3', $buffer);
echo $buffer;
```

**Comment by Znote** [comment]
Might be worth checking out, if we can wrap it into a function like "setHeaderTitle($title)".
