### ISSUE TITLE
TimeZone of getClock()

### ISSUE THREAD

**Issue by Riverlance** [Znote/ZnoteAAC#276]
This makes any sense?

https://github.com/Znote/ZnoteAAC/blob/master/config.php#L54

`if ($adjust) $adjust = (1 * 3600); // Adjust to fit your timezone.` of function getClock().
Because it always adds 1 hour, no matter what if $adjust is true.
I think it would fit the user timezone, as it says.

Thanks, @Znote ! (:

**Comment by Znote** [comment]
Change 1 * 3600 to 0 * 3600

**Comment by Znote** [comment]
Change the 1 * 3600 to whatever fit the timezone you want, and it will work. (etc 2 * 3600 to adjust +2 hours).

**Comment by Riverlance** [comment]
I thought it would get the time zone value automatically from the user computer. xd
So, don't you think it should has a value like `$config['timezone'] = -7;`?

**Comment by Znote** [comment]
It uses the date function, so if you configure the date and timezone properly on the host machine, it should return correct timestamps. Then just set adjust to 0. (instead of X * 3600)
