### ISSUE TITLE
Duplicate ID znote_accounts

### ISSUE THREAD

**Issue by glombers** [Znote/ZnoteAAC#280]
I do not know what it is due but at compile TFS 1.2 in the online lists are 2 characters. I would add that it is an original schema.sql. When setting up an account on the server 1 duplicate id

http://prntscr.com/eb4rd1
Online list:
http://prntscr.com/eb4s9x
Assuming that the first account on the server duplicates 1 ID

**Comment by glombers** [comment]
https://otland.net/threads/znote-aac-1-4-tfs-0-2-13-tfs-0-3-6-0-4.166722/page-59#post-2468729

**Comment by Znote** [comment]
This query can be executed in phpmyadmin:
https://gist.github.com/Znote/64bbfc40fa409c2e5661520a0daeb7f3

It will:
Remove duplicates. 
Repair accounts and players if they existed before Znote AAC was installed.

**Comment by glombers** [comment]
WORK!
