### ISSUE TITLE
Google safebrowser false positive screws up OT servers

### ISSUE THREAD

**Issue by Znote** [Znote/ZnoteAAC#289]
Figure out what google don't like and get rid of it. 
So far I think they consider http://otland.net (without https) insecure and dangerous. 

![safes](https://cloud.githubusercontent.com/assets/1552144/24211926/e424ba3a-0f2d-11e7-8b59-4956d5dd1f75.JPG)

Related thread:
https://otland.net/threads/acc-maker-site-marked-as-unsafe-by-google.250533/

**Comment by kito2** [comment]
All links to otland are confirmed as malicious software. Try checking credits.

**Comment by Tarek1337** [comment]
I had this issue aswell, I thought it was related to my client but after deleting every link related to OTLand, such as OTLand profiles and OTLand ip changer the warning was removed.
