### ISSUE TITLE
Paysafecard and pagseguro code

### ISSUE THREAD

**Issue by jlskelin** [Znote/ZnoteAAC#292]
Hello first time here i have a question is it possible to make a code for paysafecard?About pagseguro can anyone here explain how to make it working im not form Brazil is it possible to make pagseguro to work ?

**Comment by gpedro** [comment]
Pagseguro is something like Brazilian Paypal but you can receive $$ just in a Brazilian Bank Account (Banco do Brasil, Santander, Itau, Bradesco e Caixa Economica Federal).

**Comment by jlskelin** [comment]
Aha i see so if im not from brazil i cant make that right ?

**Comment by gpedro** [comment]
that's right ;P
