### ISSUE TITLE
paygol

### ISSUE THREAD

**Issue by OPfeajoief13** [Znote/ZnoteAAC#296]
It's not adding points.

**Comment by Znote** [comment]
Make sure to configure correct paygol ID in config.php
And login on paygol and configure IPN to paygol_ipn.php

**Comment by OPfeajoief13** [comment]
Doesn't work

**Comment by Znote** [comment]
Check your access.log file and see if paygol_ipn.php is ever contacted
If it is, check your error.log fileto see if there are any errors associated with the paygol_ipn.php page. 
In windows if using Uniform server, you can find these files in UniServerZ\core\apache2\logs
In linux, /var/log/ apache2/nginx/lighttpd should do the trick.

**Comment by OPfeajoief13** [comment]
I solved it by adding the ip in the $_SERVER['REMOTE_ADDR'] that the access.log gave me from paygol_ipn.php.

**Comment by glombers** [comment]
@OPfeajoief13  But what address did you add? Test it to make it work for everyone, not just you

**Comment by OPfeajoief13** [comment]
Alright

**Comment by glombers** [comment]
What web server are you using? My nginx was working fine

**Comment by OPfeajoief13** [comment]
windows, uniserv

**Comment by glombers** [comment]
@OPfeajoief13  Personally, I would recommend you Linux debian or ubuntu windows for public hosting in practice it seems easier but is on the way you can meet probelms like you have.

**Comment by rudger** [comment]
Right now Im on Linux Ubuntu but now my paygol_ipn is never contacted. How come?

**Comment by OPfeajoief13** [comment]
@glombers, @Znote

**Comment by glombers** [comment]
U have `PHP cURL` ? Install it `sudo apt-get install php5-curl` and restart the web server as you have apache2 `service apache2 restart` If you have nginix you do not need it. You can still look for problems on otland 

1. https://otland.net/threads/znote-aac-paypal-points-problem.251538/
2. https://github.com/Znote/ZnoteAAC/issues/122
3. https://github.com/Znote/ZnoteAAC/issues/67

**Comment by rudger** [comment]
Weird, paypal works, paygol doesnt

**Comment by rudger** [comment]
@glombers, @Znote

**Comment by Raggaer** [comment]
Paygol changed the way they work
