### ISSUE TITLE
Invite character to a guild bug

### ISSUE THREAD

**Issue by peonso** [Znote/ZnoteAAC#303]
If the character is already invited to another guild the page don't handle it and displays a sql error.

**Comment by peonso** [comment]
I made this really poor work around.

	if (!empty($_POST['invite'])) {
		if (user_character_exist($_POST['invite'])) {
			// Make sure they are not in another guild
			
			if ($config['TFSVersion'] != 'TFS_10') {
				$charname = sanitize($_POST['invite']);
				$playerdata = mysql_select_single("SELECT `id`, `rank_id` FROM `players` WHERE `name`='$charname' LIMIT 1;");
				$charid = $playerdata['id'];
				$membership = ($playerdata['rank_id'] > 0) ? true : false;
				$alreadyinvited = mysql_select_single("SELECT `player_id` FROM `guild_invites` WHERE `player_id`='$charid' LIMIT 1;");
			} else {
				$charid = user_character_id($_POST['invite']);
				$membership = mysql_select_single("SELECT `rank_id` FROM `guild_membership` WHERE `player_id`='$charid' LIMIT 1;");
			}
			if (!$alreadyinvited) {			
				if (!$membership) {
					// 
					$status = false;
					if ($inv_data !== false) {
						foreach ($inv_data as $inv) {
							if ($inv['player_id'] == user_character_id($_POST['invite'])) $status = true;
						}
					}
					foreach ($players as $player) {
						if ($player['name'] == $_POST['invite']) $status = true;
					}
					
					if ($status == false) {
						guild_invite_player($charid, $gid);
						header('Location: guilds.php?name='. $_GET['name']);
						exit();
					} else echo '<font color="red" size="4">That character is already invited(or a member) on this guild.</font>';
				} else echo '<font color="red" size="4">That character is already in a guild.</font>';
			} else echo '<font color="red" size="4">That character is already invited to another guild.</font>';			

		} else echo '<font color="red" size="4">That character name does not exist.</font>';
	}

**Comment by Znote** [comment]
Identified 2 issues:
When you are invited to 2 guilds
- Accepting one of them works, but you are still invited to the other guild, which cause 
  - SQL error if you attempt to join it. (duplicate primary key in guild_membership)
      - Fix = See if a player is already member of a guild before trying to let them join
- When successfully joining a guild, you are still invited to other guilds who wants you in
  - creating this problem in the first place
      - Fix = On successful guild join, remove all guild invitations of this player
