### ISSUE TITLE
SQL Error while creating/updating new forum board.

### ISSUE THREAD

**Issue by slawkens** [Znote/ZnoteAAC#305]
This is the error I get when trying to create/update new forum board.

![Bug](https://preview.ibb.co/dyvdYa/Bildschirmfoto_2017_09_04_um_14_28_40.png)

**Comment by Znote** [comment]
https://github.com/Znote/ZnoteAAC/blob/master/forum.php#L216-L224

We probably need to return 0 if the $values is false. I think the sql drivers have gotten more strict and this wasn't neccesary before?
