### ISSUE TITLE
Marketplace - Possible to search for specific item

### ISSUE THREAD

**Issue by amalgamnacke** [Znote/ZnoteAAC#31]
A normal use case for the marketplace could be to checkout a specific item that you're about to put up for sale on the in-game market. You would do this to get a grip on what the current price is and maybe investigate the history prices.

But what if the item you're looking to put up for sale is not currently being auctioned? Then a search/browse history function would come in handy, right?
##

**Comment by Pwntus** [comment]
I wouldn't make a separate search database since we already have this:
https://github.com/Znote/ZnoteAAC/blob/master/engine/function/itemparser/itemlistparser.php#L33

If we then run *getItemIdByName($name)* for a search query we can get the item id and make the search.
