### ISSUE TITLE
WARNING! You may get hacked trough forum, disable it!

### ISSUE THREAD

**Issue by kito2** [Znote/ZnoteAAC#315]
Today received log of 140 MB and error.log of 15.000 MB, the forum is vulnerable to be hacked.

**Comment by kito2** [comment]
Information: https://otland.net/threads/warning-znote-forum-vulnerable-of-being-hacked.255546/

**Comment by kito2** [comment]
Some contacts told me that would be better to change _GET to post forms.

**Comment by Znote** [comment]
My reply in your information thread:
https://otland.net/threads/warning-znote-forum-vulnerable-of-being-hacked.255546/#post-2477555

Counter conclusion: The forum is not vulnerable to be hacked.
