### ISSUE TITLE
[Question/enhancement?]Would be possible that znote allows players samples as geisor?

### ISSUE THREAD

**Issue by Felipe1993** [Znote/ZnoteAAC#319]
Hello @Znote 
Well im working on my project that i left behind two years again
and im trying to make possible to use this code `UPDATE `players` SET `loss_mana` = 0, `loss_skills` = 0;`
to avoid players loss skills and ml but only affect to created players non  the new ones for that i need samples(pala,kina,druid,sorc,rookstayer) and with you website/database it's not possible :'( .
also i've tested creatureevents scripts but they don't works or bug my server and i don't want to use geisor
i have this code but it causes corpses dissapear
`function onDeath(cid, corpse, killer)
doPlayerSetLossPercent(cid, PLAYERLOSS_EXPERIENCE, 15)
doPlayerSetLossPercent(cid, PLAYERLOSS_SKILLS, 0)
doPlayerSetLossPercent(cid, PLAYERLOSS_MAGIC, 0)
end
`
in the past when i was working on this project i had to use geisor to make this possible.... 
so would be this possible?

regards and  pd: this is a great project ^^

**Comment by Znote** [comment]
It would be possible, but stupid. I don't like sample characters. Lots of bugs and bad code tends to be introduced with sample characters.

You can configure vocations and their hp/mana/cap per level here:
https://github.com/Znote/ZnoteAAC/blob/master/config.php#L270-L359

You can configure vocation level and skills here:
https://github.com/Znote/ZnoteAAC/blob/master/config.php#L431-L519

You can configure other character values here: (such as loss_mana, loss_exp, loss_skills)
https://github.com/Znote/ZnoteAAC/blob/master/engine/function/users.php#L1222-L1287

You can also customize these values based on vocation IDs
```php
	if ($vocation === 1) {
		$import_data['level'] = 8;
		$import_data['experience'] = level_to_experience(8);
	}
```

**Comment by Felipe1993** [comment]
thanks znote, what about items? that's why im looking for something like character sample
btw regards from otland im cipsoftstinks ^^

**Comment by Felipe1993** [comment]
i found your first items lua @Znote srry foy my newbie questions thanks for all
