### ISSUE TITLE
How embed a youtube video at news sections in the website?

### ISSUE THREAD

**Issue by Felipe1993** [Znote/ZnoteAAC#320]
Hello @Znote 
i'been stuck on this for a while and the question is How embed a youtube video at news sections in the website? i have looked tutorial at support sections etc in otland but doesn't works could you give me an example please?

here are some videos

https://www.youtube.com/watch?v=Y7QjY1xqA24

https://www.youtube.com/watch?v=Gg_TPYseMgY

https://www.youtube.com/watch?v=5g0kClMPHPk

regards

**Comment by Znote** [comment]
Supported tags:
https://github.com/Znote/ZnoteAAC/blob/aa4d22654d97852c1569a495e9ebb3a9c31f249d/index.php#L58-L75

If you look at video ID in this link:
https://www.youtube.com/watch?v=Y7QjY1xqA24

It says v=**Y7QjY1xqA24**

So you add: 

[youtube]**Y7QjY1xqA24**[/youtube]

**Comment by glombers** [comment]
@Felipe1993 you add an editor which is available in admin news
![enter image description here](https://i.imgur.com/8Wbf9PF.png)
