### ISSUE TITLE
Bug with paypal.

### ISSUE THREAD

**Issue by Anastaciaa** [Znote/ZnoteAAC#321]
Hello,
Sometimes i have this bug in znote_paypal and i think ppls doesn't recieve points but it happens only for some players. What might be wrong? this is error:

ERROR: Invalid data. cmd=_notify-validate&mc_gross=-8.39&protection_eligibility=Eligible&payer_id=HNT4L66N3QT3L&payment_date=02%3A47%3A28+Mar+24%2C+2018+PDT&payment_status=Reversed&charset=windows-1250&first_name=Marcin&mc_fee=-0.61&notify_version=3.9&rea

or should i use this prototype?
https://gist.github.com/Znote/515e96a0de55ba44998fe88053033964

**Comment by Anastaciaa** [comment]
Where is that paypal doc?

**Comment by Znote** [comment]
A bit of a stale request, there has been several updates to the paypal.ipn script since 2018, so closing this.
