### ISSUE TITLE
PHP Fatal error

### ISSUE THREAD

**Issue by dutchdragon3** [Znote/ZnoteAAC#322]
Can i paste the website in a map to host is en start up the site for the first time ill get this error 

PHP Fatal error:  Class 'mysqli' not found in C:\WebHosting\tibia\engine\database\connect.php on line 278

How can i fix this

**Comment by dutchdragon3** [comment]
im using ISS from win server 2012  with a manual install php

**Comment by Znote** [comment]
In the PHP installation directory
In any (or all) of these files:
php.ini
php_development.ini
php_production.ini

You need to remove the commenting ( ; symbol ) from php_mysqli, or add it if it doesn't exist.
![image](https://user-images.githubusercontent.com/1552144/40916044-8ed39968-67fe-11e8-9531-21d2395332e0.png)

If you don't have the php_mysqli.dll file, you can download apache or uniform server just to grab it, they already package it with php.

**Comment by dutchdragon3** [comment]
i did remove the ; but still getting the same error

**Comment by Znote** [comment]
Do you have the php_mysqli.dll file in php/extention folder?
Did  you restart the computer (or ISS/PHP process) to ensure the file was properly reloaded?

**Comment by dutchdragon3** [comment]
yes i have and i did

**Comment by Znote** [comment]
Are you certain the .ini file you edited is correct? And that it is saved as a configuration file (ini, not a txt file)?

The mysqli class directly derives from php_mysqli. So if you get this error message, it means that php_mysqli extention is not correctly loaded. 

Unfortunately I don't have any experience setting up ISS with PHP myself, always used Uniform server. Only used linux for production.
