### ISSUE TITLE
Support for OTSVN 0.6.5 // OTHIRE

### ISSUE THREAD

**Issue by Felipe1993** [Znote/ZnoteAAC#329]
@Znote 

Hello well im making or openning this issue to disccuss or say that Znoteacc should handle these old distro because even if they are "old" distros, they re being very used nowdays to hosts server like 8.6 - 8.7-7.72
since these distros are very stable. but they have no support regarding to website
for example othire. I and many other users have to use a znoteacc website converted by peonso to handle othire, but this web is so old and lack of many functions and updates that are made by you.
so i wonder could be this possible?

regards

**Comment by Felipe1993** [comment]
bump

**Comment by Znote** [comment]
It is unfortunately too time consuming for me to support otsvn alongside any of the other distributions. The difference in the database means alot of queries need to be rewritten and specific to the version. 

I am a bit split on what to do on the next version. I want to either get rid of cross-distro compatibility alltogether, or improve it and make a more generic model to cross compatibility that does not need so much conditional versioning logic in the page specific code. If I choose to improve cross distro compatibility, its gonna be a lot of work, but otsvn support would probably be added. Assuming I can grab a good copy of an OT server that uses otsvn. (I won't add support for something I cant actively test myself).

**Comment by Nottinghster** [comment]
Well, I can do that in my free time, since I was the first one who converted the Znote AAC to OTHire, it's kinda easy to make it work with OTHire/OTServ_SVN

**Comment by Nottinghster** [comment]
You can follow here

https://github.com/Nottinghster/ZnoteAAC

From time to time, I'll make some pull requests, but only after testing the changes

**Comment by Znote** [comment]
Thanks to @Nottinghster 
This is fixed in #330
