### ISSUE TITLE
[Suppport / question ]With weird issue related to rewrite php rule

### ISSUE THREAD

**Issue by Felipe21** [Znote/ZnoteAAC#339]
Hello @Znote 
and everyone who'll read or is reading this 

Im using latest znote (Clean Version to test this)

I edited.htacces to remove the php extension and every page works
but one of the most important isn't... When i try to acces to my account i get instantly redirected to index.php or the main page so i can access to accounts via website
OBSERVATION: This only appears when i added the code to remove php extension from url

can anyone try to help me out with this? 
i have looked a lot betweens files but i don't get it ;S

i edited .htaccess file from this:
```
Options +FollowSymLinks
RewriteEngine On
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule ^(.+)\.php$ /characterprofile.php?name=$1
```
 to this(i took the code in a forum):
```
Options +FollowSymLinks
RewriteEngine On
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule ^(.+)\.php$ /characterprofile.php?name=$1

# Unless directory, remove trailing slash
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule ^([^/]+)/$ http://relicaria.ml/$1 [R=301,L]


# Redirect external .php requests to extensionless url
RewriteCond %{THE_REQUEST} ^(.+)\.php([#?][^\ ]*)?\ HTTP/
RewriteRule ^(.+)\.php$ http://relicaria.ml/$1 [R=301,L]

# Resolve .php file for extensionless php urls
RewriteRule ^([^/.]+)$ $1.php [L]
```

**Comment by Znote** [comment]
Could it be related to the login process?
a form on your page (like in [layout/widget/login.php](https://github.com/Znote/ZnoteAAC/blob/master/layout/widgets/login.php)) submits a login request to [/login.php](https://github.com/Znote/ZnoteAAC/blob/master/login.php#L206), which then handles that request, and if successfull rewrites the header to myaccount.php

Perhaps a session issue? Since you have a specific domain typed in your rewriterules?

**Comment by Felipe21** [comment]
> Could it be related to the login process?
> a form on your page (like in [layout/widget/login.php](https://github.com/Znote/ZnoteAAC/blob/master/layout/widgets/login.php)) submits a login request to [/login.php](https://github.com/Znote/ZnoteAAC/blob/master/login.php#L206), which then handles that request, and if successfull sends a header request for myaccount.php
> 
> Perhaps a session issue? Since you have a specific domain typed in your rewriterules?

Yes indeed it's related to login.php  because with few changes in the .htaccess code its shows me that" "login" doesn't exists  all this  was tested with clean website

how i can fill or complete a form on my login.php to submit the requeried request by myaccount?

thanks @Znote
