### ISSUE TITLE
Nostalrius - Item parser to go through items.srv

### ISSUE THREAD

**Issue by Znote** [Znote/ZnoteAAC#344]
Nostalrius is using a different items file that is not structured in XML. 
https://github.com/TwistedScorpio/Nostalrius/blob/master/data/items/items.srv

**Comment by tarantonio** [comment]
Any ETA to get ZnoteAAC working with Nostalrius?

**Comment by Znote** [comment]
https://github.com/Znote/ZnoteAAC/issues/355#issuecomment-477577400
