### ISSUE TITLE
Character Auction

### ISSUE THREAD

**Issue by gregorecruzeiro** [Znote/ZnoteAAC#345]
**When I am going to put a character for sale, the following message appear**s.

string(84) " UPDATE `players` SET `account_id` = 5 WHERE `id` = 2 LIMIT 1; " 
(query - SQL error) 
Type: voidQuery (voidQuery is used for update, insert or delete from database)

Cannot add or update a child row: a foreign key constraint fails (`global-znote`.`players`, CONSTRAINT `players_ibfk_1` FOREIGN KEY (`account_id`) REFERENCES `accounts` (`id`) ON DELETE CASCADE)

**Comment by Znote** [comment]
```php
$config['shop_auction'] = array(
	'characterAuction' => false, // Enable/disable this system
	// Account ID of the account that stores players in the auction.
	// Make sure storage account has a very secure password!
	'storage_account_id' => 5, // Separate secure account ID, not your GM.
	'step' => 5, // Minimum amount someone can raise a bid by
	'step_duration' => 1 * 60 * 60, // When bidding over someone else, extend bid period by 1 hour.
	'lowestLevel' => 20, // Minimum level of sold character
	'lowestPrice' => 10, // Lowest donation points a char can be sold for.
	'biddingDuration' => 1 * 24 * 60 * 60, // = 1 day, 0 to disable bidding
	'deposit' => 10 // Seller has to add 10=10% deposit to auction which he gets back later.
);
```

You need to create a new account, with a strong password, and then see what account ID that account is (you can see in phpmyadmin -> accounts). Remember account ID, not name. 
And then you need to edit **storage_account_id** to use that account id. This is used as a "storage" where players are temporarily transferred to while auction is ongoing.

**Comment by gregorecruzeiro** [comment]
Sorry for my ignorance, the system works perfectly

**Comment by Znote** [comment]
I expect more people to run into this, so I am considering doing a check to ensure storage_account_id actually exist before running the query. That way I could basically tell anyone who hasn't configured it properly what I just told you now. 

Might also be worth setting account_id to 999999 to avoid some lucky account_id 5 player getting a sudden rush of free characters on their account. x) But I fear some hosting is gonna write account name (like a retro account name with numbers) instead of the actual account id if I do that... 

hmmm

**Comment by ricardorsayt** [comment]
Hello Znote, I don't know if this is the correct area, but I'll take the opportunity to ask you, the AuctionChar system works perfectly on my 8.0 tfs 1.2 server, however ... when paying the person who sold it, it is not paid. do not report any error ... if you have any information that can help me, thank you very much.

**Comment by Znote** [comment]
@ricardorsayt 
Fixed here:
https://github.com/Znote/ZnoteAAC/commit/1ae01ee342afeadd8724b0c72094f2251134e66b

**Comment by kungen32** [comment]
Today im here, and i have found solution also.. is the number 5, ( has 50000 ) in my case. but for these maybe, one day people explain more easly for nuubs.

// Account ID of the account that stores players in the auction.  <----- This line On ' Storage Account ID ' , si more understandable, than the ' Separate secure account id ' 
		// Make sure storage account has a very secure password!
		'storage_account_id' => 50000, // Separate secure account ID, not your GM.  <------ Instead this 
		'step' => 5, // Minimum amount someone can raise a bid by

A nuub, this don't understand it, if the comment is on the line, is fine to understand, but in storage account ' Separate Secura Account Id not your gm, there i try understand why separate, who, where ? But the correct line is 2 Lines upper...

Is like talking: Can you come , there, give me this, and tell to him what i say ( Where who, what ? ).
Let's talk little, let's talk well.
