### ISSUE TITLE
characterprofile style

### ISSUE THREAD

**Issue by gregorecruzeiro** [Znote/ZnoteAAC#349]
After updating characterprofile.php for tables, if $ config ['htwrite'] = true;
At the bottom of the page has Address: http://127.0.0.1/PlayerName, when clicking the link, the characterprofile is opened and without the table, viewing the old style.

**Comment by Znote** [comment]
Your browser cache still remembers the old design in some cases. 
CTRL + SHIFT + C to open network inspector (Chrome/Opera), click on network tab, tick the checkbox for "disable cache", and reload the page. 

And in config.php, make sure `$config['site_url']` is not configured for demo.znote.eu, but your own web address. So you don't unintentionally land on the demo site.

**Comment by gregorecruzeiro** [comment]
the cache is clean, even using it on another computer exists the problem.
The url is configured

**Comment by Znote** [comment]
If you use xampp or uniform server, and use multiple websites. Try to set up virtual hosts with subdomains, that way you can have all sites running in the root. (but different root folder)

**Comment by gregorecruzeiro** [comment]
I did it now :)
