### ISSUE TITLE
highscores.php bug

### ISSUE THREAD

**Issue by gregorecruzeiro** [Znote/ZnoteAAC#354]
If there is no vocation in the ranking appears the error below.

For example, on the server there is only one Knight character and I search the ranking for Paladin

Warning: count(): Parameter must be an array or an object that implements Countable in highscores.php on line 123

**Comment by Znote** [comment]
Ahh yeah, it does not check if the array is false or empty before trying to loop it. Its not an issue once you get a player of each vocation. But I'll add it as a minor issue.
