### ISSUE TITLE
Accounts table doesn't contains "name"

### ISSUE THREAD

**Issue by Kuhicop** [Znote/ZnoteAAC#355]
Hello, I'm trying to run my TFS 1.2 protocol 7.4 with ZnoteAAC.

The game is working perfectly, I can join the server and play like a charm, but the website have a lot of problems because the database table columns are not as expected.

The main problem here and I hope I don't find more in a future, is that accounts are searched by name in website, and ingame are searched by id.

**Comment by Znote** [comment]
TFS 1.2 normally has accounts.name column, why doesn't yours? I presume it has been stripped away, which is a bad decition since accounts.name can be used, and can also store account number. Now its not a clean protocol downgrade of the TFS 1.2 engine, but a rewrite/restructure of the database, which makes it incompatible with the TFS 1.x server engine.

**Comment by Kuhicop** [comment]
Hello Znote, first of all I want to say thank you for your years of contribution.
You're one of the best known contributors.
Yes I'm trying with the source version of nostalrius (the distribution where Nostalrius started)
And yea, it's really hard to understand why people is trying to reinvent the wheel.
There's any ETA for this changes?

**Comment by Znote** [comment]
No ETA, my best guess is within a month or two. There is an unofficial modification of Znote AAC you could try to use if you need it asap: https://otland.net/threads/znote-change-name-to-id.262497/#post-2538850
Although I don't officialy support or maintain that version, use at own risk.

**Comment by Kuhicop** [comment]
Please, don't close this issue, I will test in few hours to integrate the actual iologindata code with the old one, I'm desktop software developer. If you can hold this issue open until tomorrow I will try my best to help others... thank you :)

**Comment by Kuhicop** [comment]
I just changed the iologindata.cpp for the original forgotten iologindata.cpp and login to account worked, but I wasn't able to retrieve the character list. And the "unnoficial fix" is giving trouble, I will wait for the official update of Znote, thanks for your time
