### ISSUE TITLE
Directory protection

### ISSUE THREAD

**Issue by gregorecruzeiro** [Znote/ZnoteAAC#357]
How to protect directory content eg api, layout?
im using linux 

yourdomain/layout
yourdomain/api

**Comment by Znote** [comment]
Its uneccesary to protect these directories. They should not reveal any confidential information.

However, if you don't want uneccesary snooping around in your sub directories, a good idea is to disable directory listing:
http://www.lostsaloon.com/technology/how-to-enable-and-disable-web-directory-listing-on-your-web-server/

**Comment by gregorecruzeiro** [comment]
Thanks for the sugestion
