### ISSUE TITLE
[Guild Leave] Error variable (guild leader possible leave)

### ISSUE THREAD

**Issue by milbradt** [Znote/ZnoteAAC#363]
function dont have result 'id':
https://github.com/Znote/ZnoteAAC/blob/master/engine/function/users.php#L514

https://github.com/Znote/ZnoteAAC/blob/master/guilds.php#L185
https://github.com/Znote/ZnoteAAC/blob/master/guilds.php#L938

Line 938 in guilds.php
`$data = get_player_guild_data($player['id']);`

I think it should be changed so:
```
$pid= user_character_id($player['name']);
$data = get_player_guild_data($pid);
```

Tested to using configs TFS_04

**Comment by Znote** [comment]
Hmm, the actual problem might instead be in: get_guild_players($gid)
https://github.com/Znote/ZnoteAAC/blob/e64032e630e2b9015e2b0ffc782414587cc5a51f/engine/function/users.php#L563

Try to replace the first part of the query
```sql
SELECT `p`.`rank_id`
```

with:
```sql
SELECT `p`.`id`, `p`.`rank_id`
```

**Comment by milbradt** [comment]
Yeah, Works!
