### ISSUE TITLE
Invite own guild to guild war

### ISSUE THREAD

**Issue by Emilianenko** [Znote/ZnoteAAC#375]
You can invite your own guild to war , can't accept it but stays on guildwar records.
![znoteguildwar](https://user-images.githubusercontent.com/28241119/71644110-18c35500-2ca2-11ea-81f8-1a937f017af6.png)

**Comment by EvilHero90** [comment]
https://github.com/Znote/ZnoteAAC/blob/98f90eb442c001fe26568ed6e3e624fb8088575f/guilds.php#L593
```php
if ($war_invite !== false && $gid != $targetGuild) {
```
not sure tho if this fully fixes it.

**Comment by Emilianenko** [comment]
> https://github.com/Znote/ZnoteAAC/blob/98f90eb442c001fe26568ed6e3e624fb8088575f/guilds.php#L593
> 
> ```
> if ($war_invite !== false && $gid != $targetGuild) {
> ```
> 
> not sure tho if this fully fixes it.

I just changed != to == and worked
`				if ($war_invite !== false && $gid == $targetGuild) {
`
