### ISSUE TITLE
Problem with guild management

### ISSUE THREAD

**Issue by Heitortadeu** [Znote/ZnoteAAC#377]
Hello!
I am having trouble with guild management, I can only create the guild after creation, when I click to manage guild the page is all white, as in the photo below. How to fix?

![Sem título](https://user-images.githubusercontent.com/58153179/71778634-135e5700-2f8f-11ea-8feb-b4c9b2741eee.jpg)

**Comment by Heitortadeu** [comment]
Someone to help me with this problem?

**Comment by Znote** [comment]
I think you have some weird url rewrite rules, the url should be website.com/guild.php, not website.com/index.php/guild.php

**Comment by Heitortadeu** [comment]
Your help was critical! Already solved, I just remove two-line URL in guild.php.

**Comment by Heitortadeu** [comment]
I just have another problem that I don't know how to solve, can you help me here? It's about "changelog", it doesn't load my changelos on the main page.


<a href="https://ibb.co/3pZZSsh"><img src="https://i.ibb.co/3pZZSsh/5Zr3tu4.jpg" alt="5Zr3tu4" border="0"></a>

if I post his script in header.php can you help me?

**Comment by Znote** [comment]
Its most likely a cache problem. You should have a cache file that stores the changelog after you create or update them. 

The file should be located in `/engine/cache/` folder and the name should be `changelog.cache.php`
Your web user might not have create access to the folder, or write access to the file. What you might wanna try is to:

1. Create the file manually (as a blank file)
2. Make sure the file permissions are correct, not owned by root. In most configurations, it should be www-data, if your running ots hosting provisional scripts, `otsmanager` might also work. 
3. Refreshing home page wont fix the issue, to test if whatever you are trying is actually working, create a new changelog, that should refresh the changelog system.

**Comment by Heitortadeu** [comment]
Still not able to reach this solution, access my site and you can see, maybe can find the problem of looking, is it possible?

Do I have to leave the file as the root owner? because the current owner of this cache file is www-data.

[http://empireserver.servegame.com/index.php](url)

**Comment by Znote** [comment]
Ohh, I see: http://empireserver.servegame.com/changelog.php

Your changelog cache files are working properly. Perhaps it is a layout issue. Could you link me the layout download your using, and I will take a look at it.

**Comment by Heitortadeu** [comment]
Can I send in your email? I made some modifications, I didn't want to create public at the moment ... If so, which email?

**Comment by Znote** [comment]
My email address is in my github profile:
https://github.com/Znote

**Comment by Heitortadeu** [comment]
Hello, I sent! Thank you so much for helping!

**Comment by Znote** [comment]
Your layout file was trying to load the wrong file:
```php
$changelogCache = new Cache('engine/cache/changelognews');
```

The correct file is:
```php
$changelogCache = new Cache('engine/cache/changelog');
```

**Comment by Heitortadeu** [comment]
Brother, thank you so much for your help, it has been crucial so far!
I'm really enjoying your site, if you need anything let me know!
