### ISSUE TITLE
onlinelist.php is missing us.png

### ISSUE THREAD

**Issue by SeeingBlue** [Znote/ZnoteAAC#378]
onlinelist.php references a us.png in the root directory that doesn't exist.

**Comment by Znote** [comment]
Or you are mixing secure and insecure web protocols. 

Does your server run SSL? Do you have your own flag host? 
Flags are by default loaded by my web host `flag.znote.eu`

https://github.com/Znote/ZnoteAAC/blob/6fd5aa5409234601043d71e48116103c00ed4742/config.php#L579-L586

My host is not running through SSL, so if your website does, you cannot load images from my host. 
The solution is to host your own flag server. 

Create a folder in your Znote AAC directory, etc call it "flags". 

Download my copy of my flag host:
http://flag.znote.eu/flags.zip

Extract the flag images into your own flag folder. 

Change server in config.php to your website, etc:

```php
'server' => 'https://yourotwebsite.com/flags' 
```

And it should correctly load the `us.png` flag, representing USA. Or any other country a user might sign up from when they login their character.

**Comment by SeeingBlue** [comment]
I got it working. Thanks for the clarification.
