### ISSUE TITLE
Add missing info for tibia 12 client

### ISSUE THREAD

**Issue by EPuncker** [Znote/ZnoteAAC#380]
There is some new info displayed in client, everything can be found here: https://github.com/marcomoa/gesior-aac/blob/27840c7ae24c8d2f30ff094e0b59c3712622377e/pages/login.php#L18

actually the only interesting and "working" one for OTs is the online player count tho 😋 

oh and put a condition to only send then of client version is 12+, because the 11 doesn't have it

**Comment by Znote** [comment]
`$config['client']` can be used to determine configured client version and what to send to the client.

**Comment by Znote** [comment]
Self reminder: Check out how two-factor authentication works on client 12
