### ISSUE TITLE
Login.php client 12

### ISSUE THREAD

**Issue by milkersky** [Znote/ZnoteAAC#382]
its loading character list and after choosing character can't connect, client 12.30

**Comment by Znote** [comment]
This is probably related to #380

**Comment by milkersky** [comment]
Im using: github.com/opentibiabr their distro and client

**Comment by Znote** [comment]
Just tested now, didnt find any issues with login. You just gotta configure it properly. 

Remember to edit `$config['gameserver']` to directly match exact same as config.lua! Especially server name else you will be stuck in character list. 
![image](https://user-images.githubusercontent.com/1552144/75095967-a5034180-559a-11ea-8936-f4a501ffce28.png)

![image](https://user-images.githubusercontent.com/1552144/75095977-bea48900-559a-11ea-8ae8-47170048bca9.png)

If client doesn't respond at all, it might try to access wrong url for website:
![image](https://user-images.githubusercontent.com/1552144/75095998-20fd8980-559b-11ea-96de-a2d1c5e49e55.png)
If you change this, remember to edit in (INSERT) keyboard write mode.

**Comment by milkersky** [comment]
thanks a lot :)

**Comment by Felipe21** [comment]
i downloaded clean znoteacc clean  serer tibia 12 but the connection is not working .. i can access to char list but not to the game

**Comment by Znote** [comment]
@Felipe21 Could you link the download to this "clean server tibia 12"? Then I can test it myself as well. 
I think the problem is wrong configuration in config.php. (See first image in [above post](https://github.com/Znote/ZnoteAAC/issues/382#issuecomment-589974439)).

**Comment by daniofordon** [comment]
help me https://otland.net/threads/client-12-40-problem-login-server.272780/#post-2627004

**Comment by Znote** [comment]
I made a Lua script to help sync login connection between AAC and ingame for protocol 11, 12+

https://github.com/Znote/ZnoteAAC/blob/master/Lua/TFS_10/revscriptsys/znote_login.lua
