### ISSUE TITLE
create guild bug

### ISSUE THREAD

**Issue by Methemia** [Znote/ZnoteAAC#385]
Guild list is empty.

string(109) "INSERT INTO `guilds` (`name`, `ownerid`, `creationdata`, `motd`) VALUES ('Staffffff', '1', '1583630902', '');"
(query - SQL error)
Type: voidQuery (voidQuery is used for update, insert or delete from database)

Field 'description' doesn't have a default value

**Comment by HalfAway** [comment]
What server engine do you use?

**Comment by Znote** [comment]
As HalfAway says, what distro are you using? Znote AAC is cross compatible between multiple distros, but I have yet to see anything with a description column in the guilds, thats what we use motd for.

**Comment by Methemia** [comment]
I'm using tfs 1.3 and the datapack of opentibiabr

**Comment by Znote** [comment]
I have submitted a patch to opentibiabr to resolve this bug, for now you can enter phpmyadmin -> select db -> SQL and run this query to fix it:
```sql
ALTER TABLE `guilds` 
CHANGE `description` `description` TEXT NOT NULL DEFAULT ''
```
