### ISSUE TITLE
Missing Rune Image

### ISSUE THREAD

**Issue by andersonfaaria** [Znote/ZnoteAAC#388]
Could you please re-upload the light stone shower rune in the website again?

![image](https://user-images.githubusercontent.com/8560144/78462286-f1b45f00-76a6-11ea-9c63-562b2922f9d9.png)

**Comment by glombers** [comment]
where the page gets photos from run show the page code is not a problem but I send you back here https://otland.net/forums/support.16/

**Comment by andersonfaaria** [comment]
> where the page gets photos from run show the page code is not a problem but I send you back here https://otland.net/forums/support.16/

the default page znote gets image items from is hosted by Znote website, that's why I'm creating an issue here; Of course I could just download all items and change the logic to pick the items image locally but we would then just ignoring one issue with the build as it is today.

@Znote could you please re-upload this item's image in your server or then make a PR with all items downloaded and the logic to point to local files?

**Comment by glombers** [comment]
[items.znote.eu](http://items.znote.eu/)

**Comment by Znote** [comment]
Could you send me the missing images? I can add them to items.znote.eu

Alternatively, you can download my image host: 
http://items.znote.eu/items.zip

And host the images yourself, with any modification you wish.

**Comment by andersonfaaria** [comment]
https://www.tibiawiki.com.br/images/8/89/Light_Stone_Shower_Rune.gif

**Comment by Znote** [comment]
Image added.
