### ISSUE TITLE
Player can create nick like a monster (if monster name have more than 2 words)

### ISSUE THREAD

**Issue by roriscrave01** [Znote/ZnoteAAC#404]
Exemple:
in config.lua this names are blocked
```
    $config['invalidNameTags'] = array(
         "pirate buccaneer", "pirate corsair", "pirate cutthroat", "pirate marauder",
    );
```

but player can create all this names.
If u block "pirate", so now player cant create any pirate.

It work will all names (if have 2 words), exemple: player can create "Black Knight" and a lot of another monsters.

**Comment by Znote** [comment]
![image](https://user-images.githubusercontent.com/1552144/83471750-c9b66180-a485-11ea-8e0a-b67aa0e72ea7.png)

**Comment by TechnicalIllusion** [comment]
Created proposed pull request. Separated "Bad words" from creature names to maintain proper logic to stop them. Created new logic to check name as a whole for multiword creature names. This will also allow users to use individual words without blockage.

**Comment by Znote** [comment]
Fixed in 
https://github.com/Znote/ZnoteAAC/pull/474
