### ISSUE TITLE
Disable Guild Nick feature

### ISSUE THREAD

**Issue by EPuncker** [Znote/ZnoteAAC#407]
Maybe we should add an option in config to disable guild nick feature (add/modify) until we solve this bug? it is possible to crash a server

https://github.com/otland/forgottenserver/issues/2561#issuecomment-633101435

**Comment by Znote** [comment]
We now have this config value:
https://github.com/Znote/ZnoteAAC/blob/5a800349157a5673771d4758993a127e06e1baa3/config.php#L626

My new dev environment is messy in regards to editor setup :/ Trying to use Atom instead of Sublime Text.

**Comment by luanluciano93** [comment]
Has this bug already been fixed?

**Comment by EPuncker** [comment]
> Has this bug already been fixed?

in tfs yes, since june 2020
