### ISSUE TITLE
error client 12

### ISSUE THREAD

**Issue by Tibiarl2** [Znote/ZnoteAAC#420]
`[Network error - Connection::parseHeader] Invalid Client Login! Server Name mismatch!` **<--
console problem**

use otservbr

`	$config['port'] = 7171; // Port number to connect to your OT.`

	$config['status'] = array(
		'status_check' => false, // Enable or disable status checker
		'status_ip' => '127.0.0.1',
		'status_port' => "7171",
	);

	// Gameserver info is used for client 11+ loginWebService
	$config['login_web_service'] = true; // loginWebService for client 11+ enabled?
	$config['gameserver'] = array(
		'ip' => '127.0.0.1',
		'port' => 7172,
		'name' => 'otservbr' // Must be identical to config.lua (OT config file) server name.
	);`

I have been working without problems in the other updates
`>> Loading config
>> Establishing database connection... MySQL 10.4.3
>> Running database manager
> Updating database to version 1 (sample players)
> Database has been updated to version 1.
> Updating database to version 2 (hireling)
> Database has been updated to version 2.
> Updating database to version 3 (account refactor)
> Database has been updated to version 3.
> No tables were optimized.
>> Loading vocations
>> Loading items
>> Loading script systems
>> Using LuaJIT 2.0.5
>> Loading lua libs
>> Loading lua scripts
>> Loading monsters
>> Loading lua monsters
>> Loading outfits
>> Checking world type... PVP
>> Loading map`

**Comment by Znote** [comment]
In config.lua, change serverName to `otservbr`

**Comment by Tibiarl2** [comment]
my config.php
`	// Gameserver info is used for client 11+ loginWebService
	$config['login_web_service'] = true; // loginWebService for client 11+ enabled?
	$config['gameserver'] = array(
		'ip' => '127.0.0.1',
		'port' => 7172,
		'name' => 'otservbr' // Must be identical to config.lua (OT config file) server name.
	);`
**my config .lua**

`-- Map
-- NOTE: set mapName WITHOUT .otbm at the end
-- NOTE: unzip the map world.rar
mapName = "otservbr"
mapAuthor = "OTServBR"
`

**Comment by Znote** [comment]
Install this Lua script for loginWebService:
https://github.com/Znote/ZnoteAAC/blob/master/LUA/TFS_10/revscriptsys/znote_login.lua

Place it in data/scripts/znote_login.lua and restart your OT. 
And test if it works. 

When you start OT server, you will get message like this:
![image](https://user-images.githubusercontent.com/1552144/84844122-0d929480-b04a-11ea-9190-18f56db99164.png)

**Comment by Tibiarl2** [comment]
I can't connect with the character yet

`> Yasir: not this time.
=============================
= Znote AAC loginWebService =
=============================
= Fixed 3 missing configurations.
=============================
= SERVER_NAME: OTServBR-Global
= IP: 127.0.0.1
= GAME_PORT: 7172
=============================

>> Loaded all modules, server starting up...
>> OTServBR-Global Server Online!

> Map size: 34143x33812.
Duplicate unique id: 25031
> Map loading time: 0.063 seconds.
[Network error - Connection::parseHeader] Invalid Client Login! Server Name mismatch!
[Network error - Connection::parseHeader] Invalid Client Login! Server Name mismatch!
`

**Comment by Znote** [comment]
Ahh right, you also need latest login.php
https://github.com/Znote/ZnoteAAC/blob/master/login.php

**Comment by Tibiarl2** [comment]
Solved thanx you!
