### ISSUE TITLE
Players  Online in client 12

### ISSUE THREAD

**Issue by sxbx23** [Znote/ZnoteAAC#425]
online players  always show the counter at "0" even if there are more players connected on the server, I tested with others ACC'S and the only one that doesn't show the amount of online players is znote, 

Znote acc:
![image](https://user-images.githubusercontent.com/65622633/85498626-133e2c00-b5ae-11ea-906c-8629921e527c.png)

Myacc:
![image](https://user-images.githubusercontent.com/65622633/85498647-1d602a80-b5ae-11ea-842c-42f7421760fd.png)

Cliente 12.20
Otservbr-Global

**Comment by Znote** [comment]
Fixed.
