### ISSUE TITLE
Link in Changelogs

### ISSUE THREAD

**Issue by RDaruish** [Znote/ZnoteAAC#427]
is there any way to put links in the changelogs to other pages on the site?
Ex: learn more about the <a href="#"> update </a>

**Comment by Znote** [comment]
A workaround is to change the text directly from phpmyadmin -> table `znote_changelog`
By adding the html element directly: 
```html
<a href="http://url.com/blabla">link text</a>
```

I intend to rewrite the news and changelog system when I have time to work with #394

**Comment by RDaruish** [comment]
Does not work, the site does not appear the link
