### ISSUE TITLE
Question/Issue event schedule in Client 12

### ISSUE THREAD

**Issue by keloke1** [Znote/ZnoteAAC#428]
https://github.com/Znote/ZnoteAAC/blob/0d3940a0e64b525a4526ed40e34ed588fd0dc52b/login.php#L50-L80

Event Schedule in client 12 needs extra configuration/code or is not implemented yet?,  I tried to uncomment lines 50, 80 in login.php but I get this error 

![image](https://user-images.githubusercontent.com/62517448/86164565-f8087a80-badf-11ea-9144-e0c6a14fe9ce.png)

**Comment by Znote** [comment]
line 51-79 represents a populated array, which should be inserted (instead of the empty one) in line 48. 
https://github.com/Znote/ZnoteAAC/blob/0d3940a0e64b525a4526ed40e34ed588fd0dc52b/login.php#L47-L49

**Comment by keloke1** [comment]
`eventlist' => array('description' => "Description text.\n\nTest",
					'startdate' => 1590979202,
					'colordark' => "#735D10", // HEX color code
					'name' => "Full Moon",
					'enddate' => 1590979202 + (300 * 24 * 60 * 60),
					'isseasonal' => false,
					'colorlight' => "#8B6D05")
			));`
`

now the error does not appear but nothing appears in the calendar. maybe  need to change the start and end date ?
idk what date format is this `'startdate' => 1590979202,`

**Comment by Znote** [comment]
This is unix timestamp. (The integer value you get from doing os.time() in Lua). 
Or alternatively, this generator seems to do the job:
https://www.unixtimestamp.com/index.php

![image](https://user-images.githubusercontent.com/1552144/86188479-0fc31b80-bb3f-11ea-892c-302695277f6f.png)

**Comment by keloke1** [comment]
it works! thanks for your help <3
