### ISSUE TITLE
Errors

### ISSUE THREAD

**Issue by luanluciano93** [Znote/ZnoteAAC#429]
1.  On the characterprofile page after enabling EnableQuests

**Warning: Invalid argument supplied for foreach() in characterprofile.php on line 843**

> https://github.com/Znote/ZnoteAAC/blob/master/characterprofile.php#L843

2.  After trying to click on give points in the admin.php

**Fatal error: Call to undefined function hash_equals() in admin.php on line 22**

> https://github.com/Znote/ZnoteAAC/blob/master/admin.php#L22

3. In characterprofile in the "Other visible characters on this account:" part, if you have one more character and he is like hide, the bar appears without a character, this is an error.

> https://github.com/Znote/ZnoteAAC/blob/master/characterprofile.php#L888-L933

**Comment by luanluciano93** [comment]
Warning: Invalid argument supplied for foreach() in C:\STYLLER\web\root\znote\engine\function\users.php on line 113

> Warning: array_values() expects parameter 1 to be array, boolean given in C:\STYLLER\web\root\znote\engine\function\users.php on line 120

**Comment by luanluciano93** [comment]
Warning: Invalid argument supplied for foreach() in **topguilds.php** on line 137

`https://github.com/Znote/ZnoteAAC/blob/master/topguilds.php#L137`

**Comment by Znote** [comment]
Should all be fixed now.

**Comment by luanluciano93** [comment]
1. **characterprofile.php** 
> The character page did not work. I tested on an account with two characters (X and Y). When the X is visible and the Y is invisible, on the page the character who is invisible has the list visible and vice versa for the other. When both are invisible or visible it works correctly.

2. **engine/function/general.php** 
> Tested and everything is correct.

3. **engine/function/users.php** 
> When the support page was updated, the users.php file gave the error. The error stopped, but there is no support.

4. **topguilds.php** 
> I don't know if it's correct, I have a guild war ended with 15 deaths in total and even so the topguilds page is listed as: No frags yet.

**Comment by Znote** [comment]
> 1. **characterprofile.php**
> 
> > The character page did not work. I tested on an account with two characters (X and Y). When the X is visible and the Y is invisible, on the page the character who is invisible has the list visible and vice versa for the other. When both are invisible or visible it works correctly.
> 
> 1. **engine/function/general.php**
> 
> > Tested and everything is correct.
> 
> 1. **engine/function/users.php**
> 
> > When the support page was updated, the users.php file gave the error. The error stopped, but there is no support.
> 
> 1. **topguilds.php**
> 
> > I don't know if it's correct, I have a guild war ended with 15 deaths in total and even so the topguilds page is listed as: No frags yet.

1. Fixed in [latest commit](https://github.com/Znote/ZnoteAAC/commit/297db6029df648c4560a54a32ed1f1465c01811b), forgot to omit results if searched char is hidden. 
3. Are there any staffs on the server yet? What group id/account type they got?
4. Could be an issue with the SQL query perhaps. What happens when you execute this query in phpmyadmin?:
```sql
SELECT 
	`g`.`id` AS `id`, 
	`g`.`name` AS `name`, 
	COUNT(`g`.`name`) as `frags` 
FROM `players` p 
LEFT JOIN `player_deaths` pd 
	ON `pd`.`killed_by` = `p`.`name` 
LEFT JOIN `guild_membership` gm 
	ON `p`.`id` = `gm`.`player_id` 
LEFT JOIN `guilds` g 
	ON `gm`.`guild_id` = `g`.`id` 
WHERE `pd`.`unjustified` = 1 
GROUP BY `name` 
ORDER BY 
	`frags` DESC, 
	`name` ASC 
LIMIT 0, 10;
```

**Comment by luanluciano93** [comment]
> 1. Fixed in [latest commit](https://github.com/Znote/ZnoteAAC/commit/297db6029df648c4560a54a32ed1f1465c01811b), forgot to omit results if searched char is hidden.
now if only one player has hidden, all are hidden by the site.

> 2. Are there any staffs on the server yet? What group id/account type they got?
```
SELECT 
	`group_id`
FROM `players`
WHERE `group_id` > 1;
```
Showing rows 0 - 1 (2 total

> 3. Could be an issue with the SQL query perhaps. What happens when you execute this query in phpmyadmin?:
> 
> ```sql
> SELECT 
> 	`g`.`id` AS `id`, 
> 	`g`.`name` AS `name`, 
> 	COUNT(`g`.`name`) as `frags` 
> FROM `players` p 
> LEFT JOIN `player_deaths` pd 
> 	ON `pd`.`killed_by` = `p`.`name` 
> LEFT JOIN `guild_membership` gm 
> 	ON `p`.`id` = `gm`.`player_id` 
> LEFT JOIN `guilds` g 
> 	ON `gm`.`guild_id` = `g`.`id` 
> WHERE `pd`.`unjustified` = 1 
> GROUP BY `name` 
> ORDER BY 
> 	`frags` DESC, 
> 	`name` ASC 
> LIMIT 0, 10;
> ```
MySQL did not return any records
