### ISSUE TITLE
Problem with client connection.

### ISSUE THREAD

**Issue by Verkeen** [Znote/ZnoteAAC#444]
Hi. I'm using this server files "https://github.com/malucooo/otxserver-new". I compiled correctly after few hours of suffering with problems. And i'm stuck at client now, my version is 12.40.9997. On website I can make accounts, characters and everything, but when I try to log in to the game I type email, password, choose character and it says " Account name or password is not correct." Where can I find the problem ? It's weird that after choosing character i get wrong account name or password :D

**Comment by Znote** [comment]
Gameserver coniguration mismatch between config.lua and config.php probably, are you using protocol 11+? Have you tried to use znote_login Lua script?

https://github.com/Znote/ZnoteAAC/blob/master/Lua/TFS_10/revscriptsys/znote_login.lua

**Comment by Ariesmx117** [comment]
Good morning, I get the same error with the same client **12.40.9997** and this message in the .exe
`[IOLoginData :: gameworldAuthentication] Account not found!`
I am using otx4 and I already have the login in data / scripts but the error still continues.

  and I also have an error but different with client 12.51, I posted it on otland [https://otland.net/threads/client-12-51-rsa.273075/](url)

I hope and can help me.
sorry for the inconvenience

**Comment by Znote** [comment]
Confirmed to work without any issues against latest OtservBR client 12.51:
https://github.com/opentibiabr/otservbr-global/pull/1801

Tested latest version of "Develop" in otservbr 31. October 2020. 

![image](https://user-images.githubusercontent.com/1552144/97773252-7b011680-1b4e-11eb-9298-616bccfcd05a.png)

@Ariesmx117 Add this script to your data/scripts/ folder:
https://github.com/Znote/ZnoteAAC/blob/master/Lua/TFS_10/revscriptsys/znote_login.lua
