### ISSUE TITLE
New premium time method

### ISSUE THREAD

**Issue by EPuncker** [Znote/ZnoteAAC#446]
Just a reminder that we have to adapt the code according to this https://github.com/otland/forgottenserver/commit/89a08c79d8c1df83f43f90bc3615da0165ea4fa3

maybe auto-detect table name and act accordingly

**Comment by Znote** [comment]
Yeah, quite an ugly workaround though. But I think this might be the best approach. 

```sql
SHOW COLUMNS from `accounts` WHERE `Field` = 'premdays'
```
