### ISSUE TITLE
Achivements Points 

### ISSUE THREAD

**Issue by kungen32** [Znote/ZnoteAAC#465]
Hello,
I have enable achievements points , when displays some points are like bugged , 
I try found from where comes but nothing
There is any way to delete this higher numbers ?
Also i copy past for see if picture is displayed, the dragon gif into ' Backpack ' Achievement, and the picture doesnt show, maybe is layout

![chivements](https://user-images.githubusercontent.com/77188623/111864047-101a7580-895f-11eb-9b62-15fa40513cc0.png)

**Comment by EPuncker** [comment]
did you configure correctly each achievement at the config.php file? the achievements there are just examples... you need to add everything yourself, with correct storage/achievementsID values

**Comment by kungen32** [comment]
Ouch! Sorry for nubby on this, ok we will configure it so,
Thanks for the tip!

**Comment by EPuncker** [comment]
> It will be 20000+7 instead of 30002 that's correct ?

300000+7

**Comment by kungen32** [comment]
Thanks im going to modify it !

Just for know, in case i delete all achiv lines in config, points 1 , 1 , 16119029... Still showing in character.
Im going modify achievements so, thanks you !

**Comment by kungen32** [comment]
After modifications,
300007 => array(
			'Backpack Tourist',
			'If someone lost a random thing in a random place, you\'re probably a good person to ask and go find it, even if you don\'t know what and where.',
			'points' => '1'
		),

This one, doesnt show achievement in website, is in blank, and points bugged still there

This one, show correctly the achivement, 30002 => array(
			'Backpack Tourist',
			'If someone lost a random thing in a random place, you\'re probably a good person to ask and go find it, even if you don\'t know what and where.',
			'points' => '1'
		),

And points still bugged there, maybe is layout is not compatible, so i leave it disable if this wont work and was no other solution,

Thanks for your reply and help!

**Comment by Znote** [comment]
> After modifications,
> 300007 => array(
> 'Backpack Tourist',
> 'If someone lost a random thing in a random place, you're probably a good person to ask and go find it, even if you don't know what and where.',
> 'points' => '1'
> ),
> 
> This one, doesnt show achievement in website, is in blank, and points bugged still there
> 
> This one, show correctly the achivement, 30002 => array(
> 'Backpack Tourist',
> 'If someone lost a random thing in a random place, you're probably a good person to ask and go find it, even if you don't know what and where.',
> 'points' => '1'
> ),
> 
> And points still bugged there, maybe is layout is not compatible, so i leave it disable if this wont work and was no other solution,
> 
> Thanks for your reply and help!

Escape your string literals

When you define a text variable using the \' symbol, you need to escape the \' symbol inside the text, like this: \\'
```php
array(
	'Backpack Tourist',
	'If someone lost a random thing in a random place, you\'re probably a good person to ask and go find it, even if you don\'t know what and where.',
	'points' => '1'
),
```

Alternative if you don't use dquotes in the text, use those to define text vars:
```php
array(
	'Backpack Tourist',
	"If someone lost a random thing in a random place, you're probably a good person to ask and go find it, even if you don't know what and where.",
	'points' => '1'
),
```

With a code syntax highlighter, you can easily see that the text breaks the syntax with your code:
```php
array(
	'If someone lost a random thing in a random place, you're probably a good person to ask and go find it, even if you don't know what and where.'
)
```

**Comment by kungen32** [comment]
Nice, thanks, i have started 3 month ago learning, html , and all this type of codes , and now i know more!
