### ISSUE TITLE
Character Auction will be compatible with other versions?

### ISSUE THREAD

**Issue by robertjwx** [Znote/ZnoteAAC#471]
I wanna use it on 0.4, i saw this problem on forum, i'm not the only one who wants this...
https://github.com/Znote/ZnoteAAC/blob/master/auctionChar.php#L39-L43

**Comment by Znote** [comment]
I don't think so. 0.4 is really old and obsolete. I recommend you to upgrade to latest TFS version. There are barely any devs who still work on 0.4. 

If your looking for a good 8.6 distro, I encourage Nekiro's TFS downgrade:
https://github.com/nekiro/TFS-1.4-Downgrades/tree/8.60

**Comment by robertjwx** [comment]
sad, i gonna go to other aac then
think that almost all 8.6 project uses 0.4
btw, nice project
