### ISSUE TITLE
Help in to the create new character - not use spells

### ISSUE THREAD

**Issue by abreuzinzika** [Znote/ZnoteAAC#480]
when creating a new character in znote aac latest version of github, i get this error when trying to use magic on a new character

You do not have enough skill

https://prnt.sc/1hv9jfl

**Comment by Znote** [comment]
Which server version are you using?
And client protocol?

Done any modification to starting skills?
https://github.com/Znote/ZnoteAAC/blob/ec55497c5abcad662489e6616d726e749a9e1bb3/config.php#L447-L535

What did you configure in `$config['ServerEngine']`?

**Comment by abreuzinzika** [comment]
I use otx2 and the client version is 8.60 
my server is derivative, Dragon Ball.
$config['ServerEngine'] = 'TFS_03'; is my config

**Comment by Znote** [comment]
When you create a new player, that player will get a `id` value in the database. (players table).
In TFS_03 compatibility layer, there should also be a table known as `player_skills`. Does this take have any rows that reference the `player_id` -> `id` you just created?

If im not mistaken however, magic level is still stored in the `players` table. 

I'm still curious about this:
> If you change magic to etc 5, will it appear as magic level 5 in-game after you create a new character?

**Comment by abreuzinzika** [comment]
I managed to solve it by changing to maglevel 1 and redoing all vocations by user.php and config.lua. Thanks, zNote.
I have another doubt about the templates, how do I adapt a` css/css3 template.` but whenI download a free version it comes in `.html and not .php,` can you help me?
[https://prnt.sc/1i2ejx4](url)

**Comment by Znote** [comment]
> I Solved it. Thanks, zNote.
> I have another doubt about the templates, how do I adapt a` css/css3 template.` but whenI download a free version it comes in `.html and not .php,` can you help me?
> [https://prnt.sc/1i2ejx4](url)

ohh gosh I have an old video tutorial from 9 years ago, where I was nervous and my lips kept smacking its super annoying. 😱 
But it will guide you through the process of converting an html template to work with Znote AAC:
<https://www.youtube.com/watch?v=KSs2_cpMypY>
