### ISSUE TITLE
Store items image are not loaded

### ISSUE THREAD

**Issue by mofigi** [Znote/ZnoteAAC#483]
My **shop** **doesn't** load the images even though I put the images in .gif format in the folder and change them in imageServer..
**directory** of item **images**:  **/var/www/html/tibia/items** 

my **config**.php: 		
'showImage' => true,
		'imageServer' => **'http://127.0.0.1/tibia/items',** 
(this ip is fictitious, even putting the ip of my original server does not work)

[https://prnt.sc/1lzb2s4](url)

**Comment by Znote** [comment]
`'imageServer' => '127.0.0.1/tibia/items',` without `http://`

**Comment by mofigi** [comment]
hmmm ok znote, the "items" I managed to solve, but as "outfits" I didn't ..
even putting the same directory as the items, without https:// and with the correct ip of my server, the outfits don't load
config item: 		'imageServer' => 'myserverip/tibia/items', (items ok)
config outfits:  		'imageServer' => 'myserverip/tibia/outfits' (dont show outfits)
I've already checked the outfits directory and everything is fine, just like the items.

**Comment by Znote** [comment]
full path (including http or https) to outfit file, etc:
```php
'imageServer' => 'https://outfit-images.ots.me/animatedOutfits1099/animoutfit.php'
```
