### ISSUE TITLE
[suggestion] Powergamers sql column type

### ISSUE THREAD

**Issue by luanluciano93** [Znote/ZnoteAAC#499]
The columns `onlinetimetoday`, `onlinetime1`, `onlinetime2`, `onlinetime3`, `onlinetime4`, `onlinetime5`, `onlinetime6`, `onlinetime7` could not have their type changed to `smallint` taking into account that their maximum value will be **1440**.

https://github.com/Znote/ZnoteAAC/blob/74890c1ea624f5988d3bad706e422eb26ac934cf/Lua/TFS_10/globalevent%20powergamers/powergamers.lua#L36-L43

**Comment by EPuncker** [comment]
the saved value on these columns are in seconds, so a day have `86400` seconds, and `smallint` can hold only `0 to 65535`, that is why we use the next one, that is `mediumint` and can hold `0 to 16777215`

**Comment by luanluciano93** [comment]
Sorry for my stupidity, i confused the globalevents interval and found it to be performed every hour, as it is every minute. Sorry!
