### ISSUE TITLE
Login php error gesior acc

### ISSUE THREAD

**Issue by timek26** [Znote/ZnoteAAC#506]
i use otservbr global, gesior acc, login php to tibia 12 and otclient 12,72. Ichange ip in client by client editor and i got error

[https://user-images.githubusercontent.com/65622633/84103202-5f02aa00-a9e0-11ea-8035-980b54f26251.png](url)

**Comment by Znote** [comment]
Ummh... This is the repo for Znote AAC, not Gesior AAC.

If you are using Znote AAC, you can also add this file to data/scripts/ to help configure loginWebService:
https://github.com/Znote/ZnoteAAC/blob/master/Lua/TFS_10/revscriptsys/znote_login.lua
