### ISSUE TITLE
Help to add a Player Name at shop History and order

### ISSUE THREAD

**Issue by felipetmartini** [Znote/ZnoteAAC#69]
at this line

```
    // No matter which type, we will always log it.
    mysql_insert("INSERT INTO `znote_shop_logs` (`account_id`, `player_id`, `type`, `itemid`, `count`, `points`, `time`) VALUES ('$cid', '0', '". $buy['type'] ."', '". $buy['itemid'] ."', '". $buy['count'] ."', '". $buy['points'] ."', '$time')");
```

i want to make add the player ante insted of 0, so how do this? maybe make the player select some character to delivery? at the purchease? can someone plz help or improve that? 

And at order too. how make the players make orders for a specific character???

```
        mysql_insert("INSERT INTO `znote_shop_orders` (`account_id`, `type`, `itemid`, `count`, `time`) VALUES ('$cid', '". $buy['type'] ."', '". $buy['itemid'] ."', '". $buy['count'] ."', '$time')");
        echo '<font color="green" size="4">Your order is ready to be delivered. Write this command in-game to get it: [!shop].<br>Make sure you are in depot and can carry it before executing the command!</font>';
```
##

**Comment by peonso** [comment]
Would be bad to add 

    db.query("UPDATE `znote_shop_logs` SET `player_name`=`" .. player:getName() .. "` WHERE `id` = " .. q_id .. ";")

here https://github.com/Znote/ZnoteAAC/blob/master/LUA/TFS_10/talkaction%20shopsystem/znoteshop.lua#L26, and change  `player_id int(11) NOT NULL` for `player_name varchar(255) NOT NULL` in  `znote_shop_logs` so it could be fetched by `admin_shop.php`
